language: ruby

env:
  global:
  - secure: Pr9BuRQK75t3phnU6oiviZPJs5fHN2LiipB38gHdT7q9YRgTTfoOe/4Tnnvb0I4tsy+aeOntToJ1v4hLnrEooYrgJ03rscbDik3bkg+CoFW1ieOXnlB1fbK29XTSbUKHDfPnMzryn10QeS9B1j6FLSm+VT2lEXTYIySJa958gPOpNW17brVfIj2ZwtYqpJ7yZmJwNCt1e92sHf2WEyeIE/oJZ4wkMOxLTDz8Pz5PbSVCWYAfHwvbYPZdbxpHAP9lk1//E39fgzmsVEkZH39Ycf2T1DEJBZFKbmcZU+bgBPk4+7zRVRzGpKTy76xCvM+xEnD0mbWV9adCduer1iXKhdN2It/rJxOY1wCrlOXoz26SXKzOHUVKZ0XgweaU+ErQm9JGWW8VvlqWIW2t1vwEHYIwjTo7dH4tJV6boA5eDWKzJV+fYUmpCtnkykq3PvkeuLulHAxFRZkTMhH+mHh8imZ6NGXAvWAGy93VjrQ8nrUJL4nFGIIMg+2s3FS4YESvc2YYrBT3QilaB5WfIRhIlxHVjlvkvg8JsGwRq8j8BuZkDame6N2Oe2m6HV9XAVXCnGD+qo2w9mHOhr5p06TuXO5QpT39PzPwo8Tg5vxQ3UxXDkfkwzgUBX5xFPuC47FsHfbZBBfMng3vtLejCCY7pdp8mTk7OtZMXzdDRdPWU04=
  - secure: buCL5HrEtz7SnfKi6xcmBqAS+Ab5vjxtHfNMWFloPZZUobWXtQHJvknC1cwPmWLobyifaYHbzER96Jro0WEQFFZXtoogcgj6mD2IlIh22v0+yOzPvaT7iVfKou8csWTuXl8KN2pvJocJ9TRF/X50UnHO/s7sedGgnAFsF6mSJiS6g8ZYdYahsOEBELzwro8CnhGgzCYfxeNw2HDg8fHJK7Rap+a1nYHu7yTTD7OuA3Vmb5XFC8nhBHG3TfcA4c9zT1yJxOPGuQpcy5VWJkRUkdXmO5Rx2BbVxnfuyoXAJhD6GyBtc7lYqgiFz600zFRoj4zApzLU95sDSn0zpl6cWCHAa+3rNE//9hZaiHkA0bOX6gHdb6VUTpnXeALwGEQwHbvnYt5OW9/NyQP7MaYDv4xjNYojMJ/07Af307t97P6zJ3QlQ8wBj0XDPHlqL1WQiDmkoJ4lWkT+45ZADT5mJXWXcECXQ50DZF7hVBzWw1+0KMBdH8q7wydXm6e9p+1/KqUdbTGB2Sm8hT98D+Nh7eoOVhCU+rYpVlIaQX4IC6H5BwD30uLiPCmfYhTsYs1hRnWUdJVFUd8EdnIgCFUnrpLlqF1yoaLZ5qKaOGmg6EOC3+TRQ0shSFq5GbR9KMM6gXyuPDCEuTJY3LKFubU/PN8ducp+GUqEMK52PsbRbMM=

services:
- docker

before_script:
- echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin

script:
- sh build.sh

after_script:
- docker images
- sh push.sh
