language: ruby

services:
- docker

before_script:
- echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin

script:
- sh build.sh

after_script:
- docker images
- sh push.sh
