language: ruby

env:
  global:
  - secure: l8u2Le3JeIG3j0AYmAYE25XMQy+iWNXA61FI71ip3pkCm8vcPWWVCfDvhfgb1n5VapzPYI3FYYOQRyLqA4pCnQzSEBrY6ocSbAXVqFFK2IL14OfgoHxsmElNsw47Z4Fd6MKDwwkfwz2RrBQsSm814fIqGRJbQhpz0Slo6jcGmqEfNS7UkN8/AyG0X3CPMrPp5Q2mc2dWZS/hBJSrI3UErLbCH4EhVux7dsQumugVVel781mN2A2gr20/qEQTVi1YPSeQZd6dhPeQIcpZKns0rwNtu9dMnphzBD85kimJKuclRu9gQDkYsZ8obXfKcOOnoFeIENsE2SJTJXXHKAEF74AN0mEjcbAdLDhWyRU23z6m7VVVoyDeByy/sNCjXVu09QKafhJ9zRI7ukWJOuAPnvk6NoyeGorM2PBr+DNsZWKthYBea5z6GjUdrvLjscwRgFpOJyLjGHkOuDwy6VIe24K7GBNCOY2ukfKOfiy15Mf62AE4nHOn98dSdvf2U8mfjcGuw74Q3ULrwupma0qZfQ726LoJNpu/RB06a6yShXQfSFZPIkCbu6rSLCTNx5qS7dyb3KKMTY44ywS7w1ApDp/lCdTdqIlbvESHI7jntXmVE6NR0noLVoAb0V4y3YtRDNEgHTy1/aYdXdBEq60xRwp3cJU5EREt0LxHpge5c/U=
  - secure: nMNVsIDM9d9zHoJdZL0jAVpRvUREwyKhvVLhAVqgiR9rVM3Mo5nZedbHJ9DbApK8I9QG8IyuDEoQjauEQiziwQrhL/+GOy89Xgx6/qwRYF9glv+gLh1SUY4cLgMgpov9NA+yLQRa2Z62tOFl/5IyoOzAHGk28fThxphb6lV+UpWzXBd1qUEBkaQdfJfzsKLY9yHun32hGBEl1v5ozsTI1jKsD5LolPUO6FHPyryKj+k4tJ9uKEYd6jzvECQ54y0v+cayS6MgDEp7AwnVVMfFNPfhIZEjpKOLoIsQq7P8f3J6BUvYr8OOEJiTaigCZ51Hu18gJXdhEph5Tr5CqHjDoJ8EUntmv6WMFTTR9CPG6y6kM9gqGaJocz1OvFUyua8pHgRDkuBpgFHYsqpSV85aVdLfwACKwFojPHfNmFOLLbsg/gA+NUzgIpSSddnB5Y+LjXgbDuiYl+J2CBlhpJ5I6gs1v+GPPUiDg24zTDehOn2Dlt9qcgRLQiE6BG7kLlJoy/ciSdnN6UkmDoQ4+VA99KeBW+qjrfL7mkNlsGGLny0qEPcsM2we6l2P4slWgeVvT/tTz9lKN5E7jfM5jmKkIadqwGGrnA0RCZwh5pO8KwNB85FnewMBD8mNwEigRg+hNJfPj2/JwAVayCrGNekssz49gd6h4gW2PJtsER5oZeI=

services:
- docker

before_script:
- echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin

script:
- sh build.sh

after_script:
- docker images
- sh push.sh
