name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    -
      uses: actions/checkout@v2
      name: Build the Docker images
      run: sh build.sh

    -
      uses: elgohr/Publish-Docker-Github-Action@master
      name: Publish the Docker images
      run: sh push.sh
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
